# Generated by Django 3.1.5 on 2021-01-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_auto_20210127_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.item')),
            ],
        ),
    ]
