# Generated by Django 3.1.5 on 2021-01-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0003_photoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='large_image_url',
        ),
    ]
