# Generated by Django 3.1.5 on 2021-02-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_remove_item_large_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='eCommerce.item'),
        ),
    ]
