# Generated by Django 3.1.5 on 2021-02-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='function',
            name='invitation_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.function'),
        ),
    ]
