# Generated by Django 3.1.5 on 2021-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='video_url',
            field=models.URLField(default='https//:www.google.com'),
            preserve_default=False,
        ),
    ]
