# Generated by Django 3.1.5 on 2021-02-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='health.doctor'),
        ),
    ]
